[package]
    name    = "producer"
    version = "0.1.0"
    edition = "2021"

[dependencies]
    tokio      = { version = "1.28.0", features = ["full"] }
    reqwest    = { version = "0.11.17", features = ["json"] }
    serde_json = "1.0.96"
    chrono     = "0.4.24"
