services:
  traefik:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--experimental.localPlugins.treblle.moduleName=github.com/momo-gg/rust-http-wasm"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik/access.log"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml:ro
      - ./plugins-local:/plugins-local:ro
      - ./logs:/var/log/traefik
    networks:
      - treblle-network

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
      args:
        - RUST_VERSION=${RUST_VERSION}
    environment:
      - CONSUMER_URL=http://traefik
      - INTERVAL_DURATION=5
    depends_on:
      - traefik
      - consumer
    networks:
      - treblle-network

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
      args:
        - RUST_VERSION=${RUST_VERSION}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.consumer.rule=PathPrefix(`/`)"
      - "traefik.http.services.consumer.loadbalancer.server.port=3000"
      - "traefik.http.routers.consumer.middlewares=treblle-middleware@file"
    networks:
      - treblle-network

  treblle-api:
    build:
      context: ./treblle-api
      dockerfile: Dockerfile
      args:
        - RUST_VERSION=${RUST_VERSION}
    ports:
      - "3002:3002"
    networks:
      - treblle-network

networks:
  treblle-network:
    name: treblle-network