http:
    middlewares:
        treblle-middleware:
            plugin:
                treblle:
                    treblleApiUrl: "http://treblle-api:3002/api"
                    apiKey: "your_api_key_here"
                    projectId: "your_project_id_here"
                    routeBlacklist: ["/blacklisted-example"]
                    sensitiveKeysRegex: "(?i)(password|pwd|secret|password_confirmation|cc|card_number|ccv|ssn|credit_score)"
                    allowedContentType: "application/json"

    routers:
        consumer:
            rule: "PathPrefix(`/`)"
            service: consumer-service
            middlewares:
                - treblle-middleware

    services:
        consumer-service:
            loadBalancer:
                servers:
                    - url: "http://consumer:3000"
