http:
  middlewares:
    treblle-middleware:
      plugin:
        treblle:
          treblleApiUrls: [
              # "http://httpbin.org/post",
              # "https://httpbin.org/post",
              # "http://treblle-api:3000/api",
              "https://rocknrolla.treblle.com",
              "https://punisher.treblle.com",
              "https://sicario.treblle.com",
            ]
          apiKey: "L8mhMopwLdNCSBdRWaF4MhDuEdN4H3kN"
          projectId: "cM4nke7Aav0Xdqnn"
          routeBlacklist: ["/ping", "/healthcheck", "/blacklisted-example"]
          sensitiveKeysRegex: "(?i)(password|pwd|secret|password_confirmation|cc|card_number|ccv|ssn|credit_score)"
          bufferResponse: false
          logLevel: "debug"
