api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"

providers:
  file:
    filename: /etc/traefik/traefik_dynamic.yml
  docker:
    exposedByDefault: false

experimental:
  localPlugins:
    treblle:
      moduleName: github.com/momo-gg/rust-http-wasm

serversTransport:
  insecureSkipVerify: true

log:
  level: DEBUG
  filePath: /var/log/traefik/traefik.log

accessLog:
  filePath: /var/log/traefik/access.log
  bufferingSize: 100

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
