http:
    middlewares:
        treblle-middleware:
            plugin:
                treblle:
                    treblleApiUrl: "http://treblle-api:3002/api"

    routers:
        consumer:
            rule: "PathPrefix(`/consume`)"
            service: consumer-service
            middlewares:
                - treblle-middleware

    services:
        consumer-service:
            loadBalancer:
                servers:
                    - url: "http://consumer:3000"
