global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

providers:
  file:
    directory: /etc/traefik
    watch: true
  docker:
    exposedByDefault: false

experimental:
  localPlugins:
    treblle:
      moduleName: github.com/momo-gg/treblle-wasm-plugin

log:
  level: DEBUG
  filePath: /var/log/traefik/traefik.log

accessLog:
  filePath: /var/log/traefik/access.log
  bufferingSize: 100

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

tls:
  certificates:
    - certFile: "/etc/certs/_wildcard.localhost.gg.pem"
      keyFile: "/etc/certs/_wildcard.localhost.gg-key.pem"
