[package]
    name    = "rust-http-wasm"
    version = "0.1.0"
    edition = "2021"

[lib]
    crate-type = ["cdylib"]

[dependencies]
    wit-bindgen = { version = "0.11.0", default-features = false, features = [
        "realloc",
        "macros",
    ] }
    wit-bindgen-rt = { version = "0.27.0", features = ["bitflags"] }
    serde = { version = "1.0", features = ["derive"] }
    serde_json = "1.0"
    waki = { version = "0.3.1", features = ["json"] }
    chrono = "0.4"

[profile.release]
    lto       = true
    opt-level = 's'
